# Generated by Django 2.2 on 2020-06-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customproductfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomProductField',
            new_name='CustomField',
        ),
    ]
